services:
  app:
    build: . # Tells docker-compose to build using the Dockerfile in the current directory
    image: genhands-be # Specifies the name for the built image
    container_name: genhands_backend_app
    restart: always
    ports:
      - "8080:3000" # Exposes port 8080 on the VM and maps it to port 3000 in the container
    # The following environment variables will be sourced from a .env file
    # created by the GitHub Actions workflow in the deployment directory.
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
